### PR TITLE
Use correct path to ssh-askpass

### PR DESCRIPTION
**Pull request by simmel**

### CODE REVIEW

**Comment by theseal** [comment]
Sorry, didn't get any notification about this PR so I missed it. The PR no longer merges.
Can you fix? 🙃

**Comment by simmel** [comment]
Updated

**Comment by theseal** [comment]
Still doesn't apply. 😢

**Comment by simmel** [comment]
:facepunch: :fireworks:

**Comment by theseal** [comment]
🍾

**Pull request merged**
